In [6]:
import pandas as pd
df=pd.read_csv(r'C:\Users\Administrator\Downloads\customer_shopping_behavior.csv')
df.head()

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually

In [7]:
df.describe(include='all')

,Customer ID,Age,Gender,Item Purchased,Category,Purchase Amount (USD),Location,Size,Color,Season,Review Rating,Subscription Status,Shipping Type,Discount Applied,Promo Code Used,Previous Purchases,Payment Method,Frequency of Purchases
count,3900.000000,3900.000000,3900,3900,3900,3900.000000,3900,3900,3900,3900,3863.000000,3900,3900,3900,3900,3900.000000,3900,3900
unique,NaN,NaN,2,25,4,NaN,50,4,25,4,NaN,2,6,2,2,NaN,6,7
top,NaN,NaN,Male,Blouse,Clothing,NaN,Montana,M,Olive,Spring,NaN,No,Free Shipping,No,No,NaN,PayPal,Every 3 Months
freq,NaN,NaN,2652,171,1737,NaN,96,1755,177,999,NaN,2847,675,2223,2223,NaN,677,584
mean,1950.500000,44.068462,NaN,NaN,NaN,59.764359,NaN,NaN,NaN,NaN,3.750065,NaN,NaN,NaN,NaN,25.351538,NaN,NaN
std,1125.977353,15.207589,NaN,NaN,NaN,23.685392,NaN,NaN,NaN,NaN,0.716983,NaN,NaN,NaN,NaN,14.447125,NaN,NaN
min,1.000000,18.000000,NaN,NaN,NaN,20.000000,NaN,NaN,NaN,NaN,2.500000,NaN,NaN,NaN,NaN,1.000000,NaN,NaN
25%,975.750000,31.000000,NaN,NaN,NaN,39.000000,NaN,NaN,NaN,NaN,3.100000,NaN,NaN,NaN,NaN,13.000000,NaN,NaN
50%,1950.500000,44.000000,NaN,NaN,NaN,60.000000,NaN,NaN,NaN,NaN,3.800000,NaN,NaN,NaN,NaN,25.000000,NaN,NaN
75%,2925.250000,57.000000,NaN,NaN,NaN,81.000000,NaN,NaN,NaN,NaN,4.400000,NaN,NaN,NaN,NaN,38.000000,NaN,NaN
max,3900.000000,70.000000,NaN,NaN,NaN,100.000000,NaN,NaN,NaN,NaN,5.000000,NaN,NaN,NaN,NaN,50.000000,NaN,NaN

In [8]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [22]:
df['Review Rating'] = df['Review Rating'].fillna(df['Review Rating'].mean())

In [23]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [24]:
df['Review Rating'].describe()

count    3900.000000
mean        3.750065
std         0.713573
min         2.500000
25%         3.100000
50%         3.750065
75%         4.400000
max         5.000000
Name: Review Rating, dtype: float64

In [25]:
df.columns=df.columns.str.lower()
df.columns=df.columns.str.replace(' ','_')
df=df.rename(columns={'purchase_amount_(usd)':'purchase_amount()'})

In [26]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount()', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [27]:
labels = ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut(df['age'], q=4, labels=labels)

In [28]:
df.head()

,customer_id,age,gender,item_purchased,category,purchase_amount(),location,size,color,season,review_rating,subscription_status,shipping_type,discount_applied,promo_code_used,previous_purchases,payment_method,frequency_of_purchases,age_group
0,1,55,Male,Blouse,Clothing,53,Kentucky,L,Gray,Winter,3.1,Yes,Express,Yes,Yes,14,Venmo,Fortnightly,Middle-aged
1,2,19,Male,Sweater,Clothing,64,Maine,L,Maroon,Winter,3.1,Yes,Express,Yes,Yes,2,Cash,Fortnightly,Young Adult
2,3,50,Male,Jeans,Clothing,73,Massachusetts,S,Maroon,Spring,3.1,Yes,Free Shipping,Yes,Yes,23,Credit Card,Weekly,Middle-aged
3,4,21,Male,Sandals,Footwear,90,Rhode Island,M,Maroon,Spring,3.5,Yes,Next Day Air,Yes,Yes,49,PayPal,Weekly,Young Adult
4,5,45,Male,Blouse,Clothing,49,Oregon,M,Turquoise,Spring,2.7,Yes,Free Shipping,Yes,Yes,31,PayPal,Annually,Middle-aged

In [29]:
frequency_mapping = {
    'Fortnightly': 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly': 90,
    'Biweekly': 14,
    'Annually': 365,
    'Every three months': 90
}

In [30]:
df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [31]:
df[['purchase_frequency_days', 'frequency_of_purchases']].head(10)

   purchase_frequency_days frequency_of_purchases
0                     14.0            Fortnightly
1                     14.0            Fortnightly
2                      7.0                 Weekly
3                      7.0                 Weekly
4                    365.0               Annually
5                      7.0                 Weekly
6                     90.0              Quarterly
7                      7.0                 Weekly
8                    365.0               Annually
9                     90.0              Quarterly

In [32]:
df[['discount_applied','promo_code_used']].head(10)

  discount_applied promo_code_used
0              Yes             Yes
1              Yes             Yes
2              Yes             Yes
3              Yes             Yes
4              Yes             Yes
5              Yes             Yes
6              Yes             Yes
7              Yes             Yes
8              Yes             Yes
9              Yes             Yes

In [33]:
(df['promo_code_used'] == df['discount_applied']).all()

np.True_

In [34]:
df=df.drop('promo_code_used',axis=1)

In [35]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount()', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [36]:
import sys
!{sys.executable} -m pip install mysql-connector-python

Collecting mysql-connector-python
  Downloading mysql_connector_python-9.6.0-cp314-cp314-win_amd64.whl.metadata (11 kB)
Downloading mysql_connector_python-9.6.0-cp314-cp314-win_amd64.whl (17.0 MB)
   ---------------------------------------- 0.0/17.0 MB ? eta -:--:--
   - -------------------------------------- 0.5/17.0 MB 1.6 MB/s eta 0:00:11
   - -------------------------------------- 0.8/17.0 MB 1.6 MB/s eta 0:00:11
   --- ------------------------------------ 1.3/17.0 MB 2.1 MB/s eta 0:00:08
   ---- ----------------------------------- 1.8/17.0 MB 2.0 MB/s eta 0:00:08
   ----- ---------------------------------- 2.4/17.0 MB 2.1 MB/s eta 0:00:07
   ------ --------------------------------- 2.9/17.0 MB 2.2 MB/s eta 0:00:07
   ------ --------------------------------- 2.9/17.0 MB 2.2 MB/s eta 0:00:07
   ------- -------------------------------- 3.1/17.0 MB 1.9 MB/s eta 0:00:08
   ------- -------------------------------- 3.1/17.0 MB 1.9 MB/s eta 0:00:08
   -------- ------------------------------- 3.4/17.0 MB 1.6 MB/s eta 0:00:09
   --------- ------------------------------ 3.9/17.0 MB 1.6 MB/s eta 0:00:09
   --------- ------------------------------ 4.2/17.0 MB 1.6 MB/s eta 0:00:09
   --------- ------------------------------ 4.2/17.0 MB 1.6 MB/s eta 0:00:09
   ---------- ----------------------------- 4.5/17.0 MB 1.5 MB/s eta 0:00:09
   ----------- ---------------------------- 4.7/17.0 MB 1.5 MB/s eta 0:00:09
   ----------- ---------------------------- 5.0/17.0 MB 1.4 MB/s eta 0:00:09
   ------------ --------------------------- 5.2/17.0 MB 1.4 MB/s eta 0:00:09
   ------------ --------------------------- 5.5/17.0 MB 1.4 MB/s eta 0:00:09
   ------------ --------------------------- 5.5/17.0 MB 1.4 MB/s eta 0:00:09
   ------------ --------------------------- 5.5/17.0 MB 1.4 MB/s eta 0:00:09
   ------------- -------------------------- 5.8/17.0 MB 1.3 MB/s eta 0:00:09
   -------------- ------------------------- 6.3/17.0 MB 1.3 MB/s eta 0:00:09
   -------------- ------------------------- 6.3/17.0 MB 1.3 MB/s eta 0:00:09
   -------------- ------------------------- 6.3/17.0 MB 1.3 MB/s eta 0:00:09
   --------------- ------------------------ 6.6/17.0 MB 1.2 MB/s eta 0:00:09
   --------------- ------------------------ 6.6/17.0 MB 1.2 MB/s eta 0:00:09
   ---------------- ----------------------- 6.8/17.0 MB 1.1 MB/s eta 0:00:09
   ---------------- ----------------------- 6.8/17.0 MB 1.1 MB/s eta 0:00:09
   ---------------- ----------------------- 7.1/17.0 MB 1.1 MB/s eta 0:00:10
   ----------------- ---------------------- 7.3/17.0 MB 1.1 MB/s eta 0:00:09
   ------------------ --------------------- 7.9/17.0 MB 1.2 MB/s eta 0:00:08
   ------------------- -------------------- 8.1/17.0 MB 1.2 MB/s eta 0:00:08
   ------------------- -------------------- 8.4/17.0 MB 1.2 MB/s eta 0:00:08
   -------------------- ------------------- 8.7/17.0 MB 1.2 MB/s eta 0:00:08
   -------------------- ------------------- 8.9/17.0 MB 1.2 MB/s eta 0:00:08
   --------------------- ------------------ 9.2/17.0 MB 1.1 MB/s eta 0:00:07
   --------------------- ------------------ 9.2/17.0 MB 1.1 MB/s eta 0:00:07
   ---------------------- ----------------- 9.4/17.0 MB 1.1 MB/s eta 0:00:07
   ---------------------- ----------------- 9.7/17.0 MB 1.1 MB/s eta 0:00:07
   ----------------------- ---------------- 10.0/17.0 MB 1.1 MB/s eta 0:00:07
   ------------------------ --------------- 10.5/17.0 MB 1.2 MB/s eta 0:00:06
   ------------------------- -------------- 10.7/17.0 MB 1.2 MB/s eta 0:00:06
   ------------------------- -------------- 11.0/17.0 MB 1.2 MB/s eta 0:00:06
   -------------------------- ------------- 11.3/17.0 MB 1.2 MB/s eta 0:00:05
   -------------------------- ------------- 11.3/17.0 MB 1.2 MB/s eta 0:00:05
   -------------------------- ------------- 11.3/17.0 MB 1.2 MB/s eta 0:00:05
   -------------------------- ------------- 11.3/17.0 MB 1.2 MB/s eta 0:00:05
   --------------------------- ------------ 11.5/17.0 MB 1.1 MB/s eta 0:00:05
   --------------------------- ------------ 11.5/17.0 MB 1.1 MB/s eta 0:00:05
   --------------------------- ------------ 11.8/17.0 MB 1.1 MB/s eta 0:00:05
   ---------------------------- ----------- 12.1/17.0 MB 1.1 MB/s eta 0:00:05
   ---------------------------- ----------- 12.3/17.0 MB 1.1 MB/s eta 0:00:05
   ---------------------------- ----------- 12.3/17.0 MB 1.1 MB/s eta 0:00:05
   ----------------------------- ---------- 12.6/17.0 MB 1.1 MB/s eta 0:00:05
   ----------------------------- ---------- 12.6/17.0 MB 1.1 MB/s eta 0:00:05
   ------------------------------ --------- 12.8/17.0 MB 1.1 MB/s eta 0:00:04
   ------------------------------ --------- 13.1/17.0 MB 1.0 MB/s eta 0:00:04
   ------------------------------- -------- 13.4/17.0 MB 1.0 MB/s eta 0:00:04
   ------------------------------- -------- 13.4/17.0 MB 1.0 MB/s eta 0:00:04
   ------------------------------- -------- 13.4/17.0 MB 1.0 MB/s eta 0:00:04
   -------------------------------- ------- 13.6/17.0 MB 1.0 MB/s eta 0:00:04
   -------------------------------- ------- 13.6/17.0 MB 1.0 MB/s eta 0:00:04
   -------------------------------- ------- 13.9/17.0 MB 1.0 MB/s eta 0:00:04
   -------------------------------- ------- 13.9/17.0 MB 1.0 MB/s eta 0:00:04
   --------------------------------- ------ 14.2/17.0 MB 995.4 kB/s eta 0:00:03
   --------------------------------- ------ 14.2/17.0 MB 995.4 kB/s eta 0:00:03
   --------------------------------- ------ 14.4/17.0 MB 991.6 kB/s eta 0:00:03
   ---------------------------------- ----- 14.7/17.0 MB 991.5 kB/s eta 0:00:03
   ----------------------------------- ---- 14.9/17.0 MB 988.7 kB/s eta 0:00:03
   ----------------------------------- ---- 14.9/17.0 MB 988.7 kB/s eta 0:00:03
   ----------------------------------- ---- 14.9/17.0 MB 988.7 kB/s eta 0:00:03
   ----------------------------------- ---- 15.2/17.0 MB 969.2 kB/s eta 0:00:02
   ----------------------------------- ---- 15.2/17.0 MB 969.2 kB/s eta 0:00:02
   ----------------------------------- ---- 15.2/17.0 MB 969.2 kB/s eta 0:00:02
   ----------------------------------- ---- 15.2/17.0 MB 969.2 kB/s eta 0:00:02
   ------------------------------------ --- 15.5/17.0 MB 935.5 kB/s eta 0:00:02
   ------------------------------------ --- 15.5/17.0 MB 935.5 kB/s eta 0:00:02
   ------------------------------------- -- 15.7/17.0 MB 916.9 kB/s eta 0:00:02
   ------------------------------------- -- 15.7/17.0 MB 916.9 kB/s eta 0:00:02
   ------------------------------------- -- 16.0/17.0 MB 914.1 kB/s eta 0:00:02
   -------------------------------------- - 16.3/17.0 MB 912.9 kB/s eta 0:00:01
   -------------------------------------- - 16.3/17.0 MB 912.9 kB/s eta 0:00:01
   -------------------------------------- - 16.3/17.0 MB 912.9 kB/s eta 0:00:01
   -------------------------------------- - 16.3/17.0 MB 912.9 kB/s eta 0:00:01
   -------------------------------------- - 16.3/17.0 MB 912.9 kB/s eta 0:00:01
   -------------------------------------- - 16.3/17.0 MB 912.9 kB/s eta 0:00:01
   -------------------------------------- - 16.5/17.0 MB 865.4 kB/s eta 0:00:01
   -------------------------------------- - 16.5/17.0 MB 865.4 kB/s eta 0:00:01
   -------------------------------------- - 16.5/17.0 MB 865.4 kB/s eta 0:00:01
   ---------------------------------------  16.8/17.0 MB 848.9 kB/s eta 0:00:01
   ---------------------------------------  16.8/17.0 MB 848.9 kB/s eta 0:00:01
   ---------------------------------------  16.8/17.0 MB 848.9 kB/s eta 0:00:01
   ---------------------------------------  16.8/17.0 MB 848.9 kB/s eta 0:00:01
   ---------------------------------------- 17.0/17.0 MB 828.1 kB/s  0:00:20
Installing collected packages: mysql-connector-python
Successfully installed mysql-connector-python-9.6.0

In [37]:
import mysql.connector
import pandas as pd

In [40]:
conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="YOUR_REAL_PASSWORD",   # ⚠ put your actual password
    database="YOUR_DATABASE_NAME"
)

print("Connected ")

ProgrammingError: 1045 (28000): Access denied for user 'root'@'localhost' (using password: YES)

In [43]:
import mysql.connector

conn = mysql.connector.connect(
    host="localhost",
    user="root",
    password="shruti123456789",
    database="shopping_db"
)

print("Connected ✅")

Connected ✅

In [44]:
from sqlalchemy import create_engine

In [45]:
engine = create_engine("mysql+mysqlconnector://root:shruti123456789@localhost/shopping_db")

In [46]:
df.to_sql('shopping_data', con=engine, if_exists='replace', index=False)

3900